[project]
name = "maa-streamlit"
version = "0.1.0"
dependencies = [
    "streamlit>=1.40.0",
    "psutil",
    "deepmerge",
    "loguru",
    "cattrs",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ipython",
    "ruff",
]
