schedule = "00:10"
enable = true

[device]
name = "X"
address = "localhost:5555"
config = "CompatPOSIXShellWithoutScreencapErr"

[[tasks]]
use = "start"

[[tasks]]
use = "recruit"

[[tasks]]
use = "infrast_X"
params = { plan_index = 1 }

[[tasks]]
use = "award"

[[tasks]]
use = "roguelike_mizuki"

[[tasks]]
use = "close"
