schedule = "00:10"
enabled = true

[device]
name = "Y"
address = "localhost:5556"
config = "CompatPOSIXShellWithoutScreencapErr"

[[tasks]]
_use = "start"

[[tasks]]
_use = "recruit"

[[tasks]]
_use = "infrast"

[[tasks]]
_use = "award"

[[tasks]]
_use = "fight"
params = { stage = "1-7" }

[[tasks]]
_use = "roguelike_mizuki"

[[tasks]]
_use = "close"
